[package]
name = "uep_MTGASeeker"
version = "0.0.1"
edition = "2024"

authors = ["Hurukan"]

[dependencies]
text-colorizer = "1.0.0"
rustc_version_runtime = "0.3.0"

[[bin]]
name = "uep_MTGASeeker"
path = "src/uep_MTGASeeker.rs"


